version: '2'
services:
  twitter-like-downloader:
    image: node:8
    environment:
      Consumer_Key: 
      Consumer_Secret: 
      Access_Token: 
      Access_Token_Secret: 
      privatter_Cookie: 
      download_path: ../pic-downloaded/
      LINE_ChannelSecret:
      LINE_AccessToken:
      LINE_UserId:
      PORT: 4283
      NODE_ENV: production
    ports:
      - "4283:4283"
    entrypoint:
      - npm
      - start
    working_dir: /app
    volumes:
      - ./:/app
      - ../pic-downloaded:/pic-downloaded
