version: '2'
services:
  twitter-like-downloader:
    image: node:8
    environment:
      Consumer_Key: 
      Consumer_Secret: 
      Access_Token: 
      Access_Token_Secret: 
      privatter_Cookie: 
      ifttt_Secret: 
      download_path: ../twitter-like-downloader/
      PORT: 4283
      NODE_ENV: production
    ports:
      - "4283:4283"
    entrypoint:
      - npm
      - start
    working_dir: /app
    volumes:
      - ./:/app
